name: Coverity Scan

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  coverity-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Download Coverity Scan tools
        run: |
          curl -L -o coverity.tgz https://scan.coverity.com/download/latest/linux64
          tar -xzf coverity.tgz
          echo "$PWD/cov-analysis-linux64-*/bin" >> $GITHUB_PATH

      - name: Build and analyze
        run: |
          meson setup -Dlibdbus=enabled build
          cov-build --dir cov-int meson compile -C build

      - name: Package analysis results
        run: tar czf coverity-output.tgz cov-int

      - name: Upload results to Coverity Scan
        run: |
          PROJECT_NAME="computexpresslink-libcxlmi"
          curl --form token=${{ secrets.COVERITY_SCAN_TOKEN }} \
               --form email=${{ secrets.COVERITY_SCAN_EMAIL }} \
               --form file=@coverity-output.tgz \
               --form version="${{ github.sha }}" \
               --form description="GitHub Actions build" \
               https://scan.coverity.com/builds?project=$PROJECT_NAME
