name: CI-Coverity-Scan
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [ ubuntu-latest ]
    permissions:
      contents: read          # allow actions/checkout to read the repo
      pull-requests: write    # allow the scan action to post PR comments
    steps:
      - name: Checkout Source
	uses: actions/checkout@v4
      - name: Coverity Security Scan
  	uses: blackduck-inc/black-duck-security-scan@v2.1.1      
	with:
	  coverity_url: ${{ vars.COVERITY_URL }}
	  coverity_user: ${{ vars.COVERITY_USER }}
	  coverity_passphrase: ${{ secrets.COVERITY_PASSPHRASE }}
	  coverity_prComment_enabled: true
	  github_token: ${{ secrets.GITHUB_TOKEN }}
